name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing ruby
          sudo apt-get update
          sudo apt-get install ruby2.6 -y
          sudo chown -R $(whoami) /var/lib/gems/2.6.0
          sudo chown -R $(whoami) /usr/local/bin
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: get twitter bearer token
        run: |
          echo Getting bear token
          twurl authoriize -c ${{secrets.twitter_key}} -s ${{secrets.twitter_secret}}
          twurl authorize --bearer --consumer-key ${{secrets.twitter_consumer_key}} --consumer-secret ${{secrets.twitter_consumer_secret}}
      - name: tweet update
        run: |
          echo posting update
          twurl --bearer -X POST '/api.twitter.com/1.1/statuses/update.json?status=Hello! github actions post' | jq -r '.'
