name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing gnupg2 jq
          sudo apt-get update
          sudo apt-get install ruby2.6 gnupg2 jq -y
          chown -R $(whoami) /var/lib/gems/2.6.0
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: tweet update
        run: twurl -X POST -H api.twitter.com "/1.1/statuses/update.json?status=Hello! github actions post" | jq
