name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing gnupg2 jq
          sudo apt-get update
          sudo apt-get install ruby2.6 gnupg2 jq -y
          sudo chown -R $(whoami) /var/lib/gems/2.6.0
          sudo chown -R $(whoami) /usr/local/bin
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: get twitter bearer token
        run: |
          echo Getting bear token
          TOKEN=$(curl -s -X POST \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Basic ${{secrets.twitter_consumer_key}}:${{secrets.twitter_consumer_secret}}' \
          --data '{"token_type":"{token_type}","access_token":"{access_token}"' \
          https://api.twitter.com "/oauth2/token" | jq -r '.access_token')
      - name: tweet update
        run: |
          echo posting update
          curl -s -X POST \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer ${TOKEN}' \
          https://api.twitter.com "/1.1/statuses/update.json?status=Hello! github actions post" | jq
