name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install ubuntu dependencies
        run: sudo apt-get install gnupg2 -y
      - name: install gems
        run: |
          echo installing rvm
          curl -sSL https://get.rvm.io | bash -s stable --ruby
          echo installing twurl
          gem install twurl
      - name: tweet update
        run: twurl -X POST -H api.twitter.com "/1.1/statuses/update.json?status=Hello! github actions post" | jq
