name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing ruby
          sudo apt-get update
          sudo apt-get install ruby2.6 -y
          sudo chown -R $(whoami) /var/lib/gems/2.6.0
          sudo chown -R $(whoami) /usr/local/bin
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: Decrypt large secret
        run: |
          sh ./scripts/decrypt.sh
        env:
          unlock: ${{ secrets.unlock }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/.twurlrc
      - name: tweet update
        run: |
          echo posting update
          twurl -X POST '/api.twitter.com/1.1/statuses/update.json?status=Hello! github actions post' | jq -r '.'
