name: Convert TODOs into Issues
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  build:
    name: Convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install ubuntu dependencies
        run: |
          echo installing gnupg2 jq
          sudo apt-get install gnupg2 jq -y
      - name: install gems
        run: |
          echo retrieving rvm public key
          gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          echo installing rvm
          curl -sSL https://get.rvm.io | bash -s stable --ruby
          echo installing twurl
          gem install twurl
      - name: tweet update
        run: twurl -X POST -H api.twitter.com "/1.1/statuses/update.json?status=Hello! github actions post" | jq
