name: Main
# This workflow converts
# builds the library
# tweets about the change in parallel
# dispatches to other repos

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          echo install npm dependencies
          npm install
      - run: npm run build
      - run: npm install -g npm-cli-login
      - run: npm-cli-login -u ${{secrets.npm_user}} -p ${{secrets.npm_password}} -e ${{secrets.npm_email}}
      - run: |
          echo publishing package
          npm publish
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing ruby
          sudo apt-get update
          sudo apt-get install ruby2.6 -y
          sudo chown -R $(whoami) /var/lib/gems/2.6.0
          sudo chown -R $(whoami) /usr/local/bin
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: Decrypt large secret
        run: |
          chmod +x ./scripts/decrypt.sh
          ./scripts/decrypt.sh
        env:
          unlock: ${{ secrets.unlock }}
      - name: tweet changes
        run: |
          echo tweeting changes
          twurl -X POST -H api.twitter.com "/1.1/statuses/update.json?status=$GITHUB_REPOSITORY" | jq
      - name: deleting secrets
        run: |
          echo deleting secrets
          rm $HOME/.twurlrc
  dispatch:
    needs: [build, notify]
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Dispatching to other repo
        run: |
          curl -XPOST -u "${{secrets.repo_user}}:${{secrets.access_token}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/chulander/demo-github-actions-app/dispatches --data '{"event_type": "publish"}'
