name: Notify
# This workflow converts TODOs into issues and CLOSES the github issue once the TODO is removed
on: [push]

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add ruby repo
        run: |
          echo adding ruby repo
          sudo apt-add-repository ppa:brightbox/ruby-ng
      - name: install ubuntu dependencies
        run: |
          echo installing ruby
          sudo apt-get update
          sudo apt-get install ruby2.6 -y
          sudo chown -R $(whoami) /var/lib/gems/2.6.0
          sudo chown -R $(whoami) /usr/local/bin
      - name: install gem
        run: |
          echo installing twurl
          gem install twurl
      - name: Decrypt large secret
        run: |
          chmod +x ./scripts/decrypt.sh
          ./scripts/decrypt.sh
        env:
          unlock: ${{ secrets.unlock }}
      - name: tweet changes
        env:
          REPO: ${{GITHUB_REPOSITORY}}
          SHA: ${{GITHUB_SHA}}
          EVENT: ${{GITHUB_EVENT_NAME}}
        run: |
          echo posting update
          twurl -X POST -d 'status=$REPO made a $EVENT change for $SHA' '/1.1/statuses/update.json'  | jq -r '.'
      - name: delete secrets
        run: |
          echo deleting secrets
          rm $HOME/.twurlrc
      - run: |
          curl -XPOST -u "${{secrets.repo_user}}:${{secrets.access_token}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/chulander/demo-github-actions-app/dispatches --data '{"event_type": "publish"}'
